<a href="https://colab.research.google.com/github/DiyaSReddy/NumPy/blob/main/Numpy_proj_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Task 1: Create a 5×5 NumPy array filled with random integers between 1 and 50
np.random.seed(42)  # For reproducibility
matrix = np.random.randint(1, 51, (5, 5))
print("Original Matrix:\n", matrix)

# Task 2: Replace all even numbers with -1 without using loops
matrix_even_replaced = np.where(matrix % 2 == 0, -1, matrix)
print("\nMatrix with even numbers replaced by -1:\n", matrix_even_replaced)

# Task 3: Compute the sum of each row and store it in a new array
row_sums = np.sum(matrix, axis=1)
print("\nSum of each row:", row_sums)

# Task 4: Compute the dot product of the matrix with its transpose
dot_product = np.dot(matrix, matrix.T)
print("\nDot product of matrix with its transpose:\n", dot_product)

# Task 5: Find the index of the maximum element in the matrix
max_index = np.unravel_index(np.argmax(matrix), matrix.shape)
print("\nIndex of maximum element:", max_index)

Original Matrix:
 [[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]

Matrix with even numbers replaced by -1:
 [[39 29 15 43 -1]
 [21 39 19 23 11]
 [11 -1 -1 -1 -1]
 [ 3 -1 -1 -1 -1]
 [-1 -1 -1 21 33]]

Sum of each row: [134 113 135  95 124]

Dot product of matrix with its transpose:
 [[4500 3312 3577 2169 3469]
 [3312 2973 3035 1995 2996]
 [3577 3035 4169 2649 2946]
 [2169 1995 2649 3009 2886]
 [3469 2996 2946 2886 3878]]

Index of maximum element: (3, 4)
