<a href="https://colab.research.google.com/github/DiyaSReddy/NumPy/blob/main/Numpy_project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Set the random seed for reproducibility
np.random.seed(26)

# 1. Generate a NumPy array (30×4) representing daily temperatures (in °C) for a month,
# with four columns: Morning, Afternoon, Evening, and Night temperatures
temp = np.random.uniform(15, 40, size=(30, 4))

# 2. Average temperature for each time of the day
avg_temp = np.mean(temp, axis=0)
print("\nAverage Temperatures: \n", avg_temp)

# 3. Hottest and coldest days of the month
hottest_day = np.argmax(np.max(temp, axis=1)) + 1
coldest_day = np.argmin(np.min(temp, axis=1)) + 1
print("\nHottest day of the month: ", hottest_day)
print("Coldest day of the month: ", coldest_day)

# 4. Days when the afternoon temperature exceeded 35°C
afternoon = np.where(temp[:, 1] > 35)[0] + 1
print("\nDays with afternoon temp > 35°C: ", afternoon)

# Moving average of temperatures over a 7-day window
moving_avg_temperatures = np.array([np.mean(temp[i:i+7], axis=0) for i in range(24)])
print("\n7-Day Moving Average Temperatures: ", moving_avg_temperatures)



Average Temperatures: 
 [30.44729318 27.31117555 26.49134017 27.93526815]

Hottest day of the month:  6
Coldest day of the month:  26

Days with afternoon temp > 35°C:  [ 5 11 12 21 29]

7-Day Moving Average Temperatures:  [[32.11369959 28.33073547 28.47014659 25.85820369]
 [33.15726035 29.15660687 28.01681985 26.33705628]
 [33.22214671 30.78785673 28.11016687 27.00277618]
 [31.57170214 30.54313517 29.50363839 26.53932345]
 [32.56327193 30.87671928 28.88587394 26.75654975]
 [32.60333    30.90797571 30.31620124 25.20463557]
 [33.42422825 31.74135174 27.61576028 25.06832231]
 [30.60621284 32.21693314 28.44579963 26.83803107]
 [29.12934599 31.36483123 26.44609575 25.40924648]
 [26.43337776 29.7718068  25.77664182 25.23114474]
 [28.84381003 31.2001278  24.9441417  25.58560347]
 [30.37975566 30.41055755 25.90128724 27.80482569]
 [29.69700353 27.25637412 25.96107044 28.8802397 ]
 [27.53377636 25.6269219  27.39163584 30.24839344]
 [27.83789559 26.31688517 25.45193633 28.38114368]
 [30.254838