<a href="https://colab.research.google.com/github/DiyaSReddy/NumPy/blob/main/sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def validate(board, i_row, j_col, num):

    # row validation
    if num in board[i_row, :]:
        return False

    # column validation
    if num in board[:, j_col]:
        return False

    # 3x3 subgrid validation
    start_row, start_col = (i_row // 3) * 3, (j_col // 3) * 3
    if num in board[start_row:start_row+3, start_col:start_col+3]:
        return False

    return True

In [ ]:
def sudoku(board):
    # arrays of cells with 0
    zeroes_array = np.argwhere(board == 0)

    # Solved
    if zeroes_array.size == 0:
        return True

    # index of the first 0 in the board
    i_row, j_col = zeroes_array[0]

    for num in range(1, 10): # 10 is exclusive

        if validate(board, i_row, j_col, num):
            # Replace the 0 with the number
            board[i_row, j_col] = num

            # recursive function to add all the numbers anf fill the complete board
            if sudoku(board):
                return True

            # backtracking
            board[i_row, j_col] = 0

    return False

In [ ]:
board = np.array([
    [0, 4, 3, 0, 5, 0, 2, 0, 7],
    [0, 2, 0, 0, 0, 4, 0, 0, 6],
    [7, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 7, 0, 1, 0, 6, 0, 0],
    [0, 1, 0, 6, 0, 8, 0, 7, 0],
    [0, 0, 6, 0, 9, 0, 8, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 9],
    [5, 0, 0, 9, 0, 0, 0, 8, 0],
    [6, 0, 1, 0, 7, 0, 5, 2, 0]
])

if sudoku(board):
    print("Final Sudoku:")
    print(board)
else:
    print("No solution found!")

Final Sudoku:
[[8 4 3 1 5 6 2 9 7]
 [1 2 9 7 8 4 3 5 6]
 [7 6 5 3 2 9 4 1 8]
 [9 8 7 4 1 5 6 3 2]
 [4 1 2 6 3 8 9 7 5]
 [3 5 6 2 9 7 8 4 1]
 [2 3 8 5 4 1 7 6 9]
 [5 7 4 9 6 2 1 8 3]
 [6 9 1 8 7 3 5 2 4]]
